name: kaggle-trends
channels:
    - conda-forge
dependencies:
  - python=3.7
  - pip
  - pip:
    - numpy
    - pandas
    - scikit-learn
    - matplotlib
    - seaborn
    - tqdm
    - dfply
    - notebook
    - jupyterlab
    - streamlit
